lang: 'en'
#Language of VipSystem
#Now available: en zh_CN
uuid: false
#Use UUID for data storage
previousGroup: false
#whether return to the previous group before activating vip after the vip expires
dataBase:
  usePool: true
  #use connection pool or not
  useMySQL: false
  #use MySQL or not
  #if enabled, you need to fill in the blanks in 'MySQL' below
  MySQL:
    address: 'jdbc:mysql://127.0.0.1:3306/minecraft?useSSL=false'
    #jdbc connection address
    #Format: 'jdbc:mysql://IP_ADDRESS/DATABASE_NAME'
    #For example 'jdbc:mysql://127.0.0.1:3306/minecraft' stands for the mysql server on '127.0.0.1' with port '3306' and database 'minecraft'
    user: 'root'
    #MySQL user name
    password: 'yourpwdhere'
    #MySQL password
    table: 'vipsys_'
    #MySQL table prefix
isGlobal: true
#Use Vault to apply VIP to global group
worlds: []
#If isGlobal disabled, apply VIP to worlds above
#Set to [] if you want to apply vip to all the worlds which are loaded by bukkit
#If you want to apply vip to the specific worlds, please turn isGlobal to false and add the world manually
############################
#isGlobal: false
#worlds:
#  - world
#  - world_nether
#  - world_the_end
#add all of your worlds here
############################
dateFormat: 'yyyy-MM-dd HH:mm:ss'
#Date format to be displayed